Adding Maven dependencies
anciuvaga/API-Testing pull request #1
Opened 2020-11-05 22:05 UTC by anciuvaga

2020-11-06 14:16 UTC, euliancom requested changes

2020-11-06 14:16 UTC, euliancom commented on pom.xml
> +    <modelVersion>4.0.0</modelVersion>gi
please remove `gi`

2020-11-06 14:16 UTC, euliancom commented on pom.xml
>  </project>
please add a new line

2020-11-06 15:04 UTC, anciuvaga commented on pom.xml
> +    <modelVersion>4.0.0</modelVersion>gi
Done 👍

2020-11-06 15:05 UTC, anciuvaga commented on pom.xml
>  </project>
Done 👍

2020-11-08 20:30 UTC, euliancom approved these changes

2020-11-08 20:30 UTC, merged