Adding GET methods,config.properties,TestUtils class, GetAPITest class
anciuvaga/API-Testing pull request #3
Opened 2020-11-11 00:18 UTC by anciuvaga

2020-11-11 09:14 UTC, euliancom requested changes

2020-11-11 09:14 UTC, euliancom commented on .gitignore
> +target/
adauga o linie noua la sfarsitul fisierului

2020-11-11 09:14 UTC, euliancom commented on src/main/resources/configs/config.properties
> +apiURL=/api/users
adauga o linie noua la sfarsitul fisierului

2020-11-11 10:37 UTC, anciuvaga commented on src/main/resources/configs/config.properties
> +apiURL=/api/users
Done

2020-11-11 10:37 UTC, anciuvaga commented on .gitignore
> +target/
Done

2020-11-12 10:56 UTC, euliancom approved these changes

2020-11-12 10:56 UTC, merged